target ‘baobei’ do
    pod 'AVOSCloud', '3.1.6.2'
    pod 'MBProgressHUD', '0.9.1'
    pod 'SDWebImage', '3.7.2'
    pod 'DateTools', '1.5.0'
    pod 'FXForms', '1.2.13'
    pod 'TTTAttributedLabel', '1.13.4'
    pod 'JVFloatLabeledTextField'
    pod 'Realm', '0.98.6'
    pod 'DOUAudioStreamer'
    pod 'AFNetworking', '~> 3.0'
    pod 'Masonry'
    pod 'NJKWebViewProgress'
    pod 'pop'
    pod 'MJRefresh'
    pod 'SSKeychain'
    pod 'ZipArchive'
    pod 'SDCycleScrollView','~> 1.61'
    pod 'FXBlurView'
    pod 'YYWebImage'
    pod 'FastttCamera'
    pod 'FastttCamera/Filters'
    pod 'IDMPhotoBrowser'
    pod 'TGCameraViewController'
    pod 'NAKPlaybackIndicatorView'
    pod 'PlayerKit', :git => 'https://github.com/xhzengAIB/PlayerKit'
    
    pod 'ContextMenu.iOS', '~> 1.1.0'
    pod "PPSSignatureView"
    pod 'RealReachability'
    pod 'ActionSheetPicker'
  pod 'BFKit'
	pod 'UMengAnalytics'

end